_target_: src.tuners.timm_tuner.TimmTuner
hparams:
  model_type:
    - efficientnet_b0.ra_in1k
    - efficientnet_b1.ft_in1k
    - efficientnet_b2.ra_in1k
    - efficientnet_b3.ra2_in1k
    - efficientnet_b4.ra2_in1k
    - efficientnet_b5.sw_in12k
    - efficientnet_b5.sw_in12k_ft_in1k
  pretrained:
    - pretrained
    - raw
  lr:
    low: 0.000005
    high: 0.00005
    log: False
  t_max:
    low: 25
    high: 100
    log: False
  eta_min:
    low: 0.0000001
    high: 0.0000005
    log: False

module_params:
  num_labels: ${num_labels}
  average: macro
  interval: step
  devices: ${devices}
  accelerator: ${accelerator}
  strategy: ${strategy}
  log_every_n_steps: ${log_every_n_steps}
  precision: ${precision}
  accumulate_grad_batches: ${accumulate_grad_batches}
  max_epochs: ${epoch}
  monitor: ${monitor}
  mode: ${tracking_direction}
  patience: ${patience}
  min_delta: ${min_delta}

num_trials: ${num_trials}
seed: ${seed}
hparams_save_path: ${hparams_save_path}