_target_: src.architectures.huggingface_architecture.HuggingFaceArchitecture

model:
  _target_: src.architectures.models.huggingface_model.HuggingFaceModel
  modality: ${modality}
  pretrained_model_name: ${pretrained_model_name}
  n_classes: ${num_labels}

num_classes: ${num_labels}
average: macro
strategy: ${strategy}
lr: ${lr}
t_max: ${t_max}
eta_min: ${eta_min}
interval: step
