_target_: src.architectures.image_architecture.ImageArchitecture

model:
  _target_: src.architectures.models.image_model.ImageModel
  model_type: ${model_type}
  pretrained: ${pretrained}
  n_classes: ${num_labels}

num_classes: ${num_labels}
average: macro
strategy: ${strategy}
lr: ${lr}
t_max: ${t_max}
eta_min: ${eta_min}
interval: step
