_target_: src.architectures.timm_architecture.TimmArchitecture

model:
  _target_: src.architectures.models.timm_model.TimmModel
  model_type: ${model_type}
  pretrained: ${pretrained}
  num_labels: ${num_labels}

num_labels: ${num_labels}
average: macro
strategy: ${strategy}
lr: ${lr}
t_max: ${t_max}
eta_min: ${eta_min}
interval: step
