_target_: src.datasets.image_dataset.UpStageDocsDataset
data_path: ${connected_dir}/data
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
image_size: ${image_size}
augmentation_probability: 0.2
augmentations:
  - rotate30
  - rotate45
  - rotate90
  - hflip
  - vflip
  - noise
  - blur
