_target_: src.datasets.multimodal_dataset.UpStageDocsDataset
data_path: ${connected_dir}/data
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
target_column_name: ${target_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
image_pretrained_model_name: ${image_pretrained_model_name}
text_pretrained_model_name: ${text_pretrained_model_name}
augmentation_probability: 0.2
augmentations:
  - rotate30
  - rotate45
  - rotate90
  - hflip
  - vflip
  - noise
  - blur
text_max_length: ${text_max_length}
