# @package _global_
defaults:
  - dataset: huggingface_upstagedocs_dataset
  - architecture: huggingface_architecture
  - tuner: huggingface_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: upstage-cv
project_dir: /home/ddang/${package_name}
connected_dir: /data/${package_name}

seed: 2024

num_labels: 17

split:
  train: train
  val: val
  test: test

batch_size: 24

split_ratio: 0.1
upload_user: klue
model_type: roberta-large
pretrained_model_name: ${upload_user}/${model_type}
text_max_length: 512

modality: text
is_backbone: False

lr: 0.00002
t_max: 50
eta_min: 0.0000025

monitor: val_MulticlassF1Score
tracking_direction: max
patience: 3
min_delta: 0

devices: 4
accelerator: gpu
strategy: ddp
log_every_n_steps: 10
precision: 32
accumulate_grad_batches: 1
epoch: 100

model_name: HuggingFace_${modality}
dataset_name: UpStageDocs
mode: train

is_tuned: tuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
save_detail: ${upload_user}_${model_type}-bs${batch_size}x${devices}x${accumulate_grad_batches}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch${epoch}.ckpt

logit_name: ${save_detail}-epoch${epoch}
submission_name: ${save_detail}-epoch${epoch}

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}